# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc


TARG=gokogiri/libxml

GOFILES=\
	lib.go\

include $(GOROOT)/src/Make.pkg
